#!/bin/bash

declare -r current_dir=$(cd "$(dirname "$0")"; pwd)
declare -r tmp_dir="${current_dir}/tmp"
declare -r go_dir="${tmp_dir}/go"
declare -r tmp_src_dir="${tmp_dir}/go/src/dep/k8s-health"

pre() {
  mkdir -p ${tmp_src_dir}
  export GOPATH=${go_dir}
}

restore_godep() {
  pushd $1 &&
    godep restore -v &&
    popd
}

save_godep() {
  pushd $1 &&
    godep save -v ./... &&
    popd
}

get_dependencies() {
  make && rm -f ${current_dir}/healthcheck
}

copy_to_go_src() {
  pushd $current_dir &&
    cp Makefile ${tmp_src_dir} &&
    cp *.go ${tmp_src_dir} &&
    popd
}

copy_from_go_src() {
  cp ${tmp_src_dir}/Godeps/Godeps.json ${current_dir}/Godeps
}

post() {
  echo "All done. If you plan on doing work with the dependencies, make sure to set your gopath. E.g.
export GOPATH=${go_dir}

Manually clean up the temporary gopath when you're done! E.g.
rm -rf ${tmp_dir}"
}

pre
get_dependencies
restore_godep ${GOPATH}/src/k8s.io/kubernetes
copy_to_go_src
save_godep ${GOPATH}/src/dep/k8s-health
copy_from_go_src
post
