#!/bin/bash

set -xe

declare -r current_dir=$(cd "$(dirname "$0")"; pwd)
declare -r ci_dir="${current_dir}/dependency_builder"

PREFIX=jswoods/k8s-health
PREFIX_BUILDER=${PREFIX}-builder
TAG=$(git rev-parse --short HEAD)

build_builder() {
  pushd ${ci_dir} &&
    docker build -t ${PREFIX_BUILDER}:${TAG} . &&
    popd
}

build_binary() {
  docker run --rm -v ${current_dir}:/src ${PREFIX_BUILDER}:${TAG}
}

build_image() {
  docker build -t ${PREFIX}:${TAG} ${current_dir}
}

push_to_registry() {
  docker push ${PREFIX}:${TAG}
}

cleanup() {
  rm -f ${current_dir}/healthcheck
}

build_builder
build_binary
build_image
push_to_registry
cleanup

exit 0
